### ISSUE TITLE
The operation delete not working ($inp['__dbid'] order mismatch)

### ISSUE THREAD

**Issue by CharlesKumar** [cybrox/crunchdb#4] opened 2018-06-21 05:16 UTC
I experienced an issue after deleting a few records, inserting a few and again tried to delete 

nothing happened...

inspected through the code
```
 private function tweak($input){
      $counter = 0;
      foreach($input as $inp){
        array_push($this->uids, $counter);
        $inp['__dbid'] = $counter;
        $this->data[] = $inp;
        $counter++;
      }
      $this->rawd = $this->data;
    }
```

The delete operation is based on ['__dbid'] which is based on $counter created in tweak function

So I temporarily reordered using array_values in delete function (like below)

```
 public function delete(){
      $this->base->tbdata['data'] = array_values($this->base->tbdata['data']);
      foreach($this->data as $d) {
        unset($this->base->tbdata['data'][$d['__dbid']]);
      }
      $this->base->tbdata['data'] = array_values($this->base->tbdata['data']);
      $this->base->_saveData();
      return true;
    }

```

kindly look through this when you go through crunchdb

**Comment by cybrox** [comment] 2018-06-22 07:12
Thanks a lot for reporting this issue and providing such detailed information!

I'll see if I can reproduce this, as soon as possible. - I think I'll be able to look into it by mid next week.

**Comment by cybrox** [comment] 2018-07-01 14:39
Hi, sorry for the late reply.

I ran a little test script and was able to reproduce your issue:

```php
$cdb->table('names')->create());
$cdb->table('names')->count());

$cdb->table('names')->insert(array("name" => "Name A"));
$cdb->table('names')->insert(array("name" => "Name B"));
$cdb->table('names')->insert(array("name" => "Name C"));
$cdb->table('names')->select(["name", "==", "Name A"])->delete();
$cdb->table('names')->select(["name", "==", "Name B"])->delete();
$cdb->table('names')->select(["name", "==", "Name C"])->delete();

// Database should be empty but contains "C"
$cdb->table('names')->select('*')->fetch();
$cdb->table('names')->count());

$cdb->table('names')->drop();
```

Thank you for providing a fitting solution. Although I don't think re-aligning the table twice is necessary. The bug is only caused by shifts from previous deletes, so using `array_values()` once after the delete (`unset`) operation should suffice.

```php
      // working delete();
      foreach($this->data as $d) {
        unset($this->base->tbdata['data'][$d['__dbid']]);
      }
      $this->base->tbdata['data'] = array_values($this->base->tbdata['data']);
      $this->base->_saveData();
      return true;
``` 

**In Conclusion**, if you want, you can file a PR to have these changes merged into the library under your name. Otherwise, I'll just commit them manually and reference this issue :) 

---

For reference:
Another method of solving this, would be modifying `_saveData` instead, so the table is aligned after every mutation. I don't think there's any other use case than the delete operation that requires this fix, though, so your solution should work fine

```php
$aligned_table = array("data" => array_values($this->tbdata["data"]));
file_put_contents($this->tbpath, json_encode($aligned_table));
```

**Comment by CharlesKumar** [comment] 2018-07-01 16:11
Hi Sven,

  thanks for getting into this and also for keeping this nice project (still a unique project in this category json database system)

   Although I've been using github for years yet to do a PR

   next time i'll do

**Closed as completed** 2018-07-15 00:59 UTC
